from __future__ import annotations

from app.scrapers.config import ScrapeConfig

SITE_CONFIGS = [
    ScrapeConfig(
        name="princesspolly",
        base_url="https://www.princesspolly.com",
        search_url="https://www.princesspolly.com/search?q={query}",
    ),
    ScrapeConfig(
        name="whitefoxboutique",
        base_url="https://www.whitefoxboutique.com",
        search_url="https://www.whitefoxboutique.com/search?q={query}",
        description_selectors=[
            "[class*='accordion__description']",
        ],
    ),
    ScrapeConfig(
        name="american-eagle",
        base_url="https://www.ae.com",
        search_url="https://www.ae.com/us/en/search?query={query}",
    ),
    ScrapeConfig(
        name="aerie",
        base_url="https://www.aerie.com",
        search_url="https://www.aerie.com/us/en/search?query={query}",
    ),
    ScrapeConfig(
        name="freepeople",
        base_url="https://www.freepeople.com",
        search_url="https://www.freepeople.com/search/?q={query}",
    ),
    ScrapeConfig(
        name="oldnavy",
        base_url="https://oldnavy.gap.com",
        search_url="https://oldnavy.gap.com/browse/search.do?searchText={query}",
    ),
    ScrapeConfig(
        name="pacsun",
        base_url="https://www.pacsun.com",
        search_url="https://www.pacsun.com/search?q={query}",
    ),
    ScrapeConfig(
        name="reformation",
        base_url="https://www.thereformation.com",
        search_url="https://www.thereformation.com/search?q={query}",
        name_selectors=[
            "h1[itemprop='name']",
            "[data-qa='pdp-product-name']",
            "[data-qa='product-name']",
            "h1",
        ],
        price_selectors=[
            "[itemprop='price']",
            "[data-qa='pdp-price']",
            "[data-qa='product-price']",
            "[class*='price']",
        ],
        size_selectors=[
            "button[data-qa*='size']",
            "button[data-size]",
            "button[name*='size']",
            "select[name*='size'] option",
        ],
        availability_selectors=[
            "[data-qa*='availability']",
            "[data-qa*='stock']",
            "[class*='availability']",
            "[class*='stock']",
        ],
        description_selectors=[
            "[data-qa='product-description']",
            "[data-qa='pdp-description']",
            "[itemprop='description']",
            "[class*='description']",
        ],
    ),
    ScrapeConfig(
        name="revolve",
        base_url="https://www.revolve.com",
        search_url="https://www.revolve.com/r/Search.jsp?search={query}",
    ),
    ScrapeConfig(
        name="sisterhoods",
        base_url="https://www.sisterhoods.com",
        search_url="https://www.sisterhoods.com/search?q={query}",
    ),
    ScrapeConfig(
        name="wearenotbasics",
        base_url="https://www.wearenotbasics.com",
        search_url="https://www.wearenotbasics.com/search?q={query}",
    ),
    ScrapeConfig(
        name="wearpact",
        base_url="https://wearpact.com",
        search_url="https://wearpact.com/search?q={query}",
    ),
    ScrapeConfig(
        name="cosstores",
        base_url="https://www.cosstores.com",
        search_url="https://www.cosstores.com/en_usd/search.html?q={query}",
    ),
    ScrapeConfig(
        name="massimodutti",
        base_url="https://www.massimodutti.com",
        search_url="https://www.massimodutti.com/us/search?searchTerm={query}",
    ),
    ScrapeConfig(
        name="nobodyschild",
        base_url="https://www.nobodyschild.com",
        search_url="https://www.nobodyschild.com/search?q={query}",
        name_selectors=[
            "h1[itemprop='name']",
            "[data-qa='product-title']",
            "[data-testid='product-title']",
            "h1",
        ],
        price_selectors=[
            "[itemprop='price']",
            "[data-qa='product-price']",
            "[data-product-price]",
            ".price__regular .price-item",
            ".price-item",
        ],
        size_selectors=[
            "button[data-option-value]",
            "button[data-value]",
            "input[name*='Size'] + label",
            "select[name*='size'] option",
        ],
        availability_selectors=[
            "[data-qa*='availability']",
            "[class*='availability']",
            "[class*='stock']",
        ],
        description_selectors=[
            "[data-qa='product-description']",
            "[itemprop='description']",
            "[class*='description']",
        ],
    ),
    ScrapeConfig(
        name="organicbasics",
        base_url="https://www.organicbasics.com",
        search_url="https://www.organicbasics.com/search?q={query}",
        name_selectors=[
            "h1[itemprop='name']",
            "[data-qa='product-title']",
            "[data-testid='product-title']",
            "h1",
        ],
        price_selectors=[
            "[itemprop='price']",
            "[data-qa='product-price']",
            "[data-product-price]",
            ".price__regular .price-item",
            ".price-item",
        ],
        size_selectors=[
            "button[data-option-value]",
            "button[data-value]",
            "input[name*='Size'] + label",
            "select[name*='size'] option",
        ],
        availability_selectors=[
            "[data-qa*='availability']",
            "[class*='availability']",
            "[class*='stock']",
        ],
        description_selectors=[
            "[class*='product__description']",
        ],
    ),
    ScrapeConfig(
        name="boody",
        base_url="https://www.boody.com",
        search_url="https://www.boody.com/search?q={query}",
    ),
    ScrapeConfig(
        name="bambooclothing",
        base_url="https://www.bambooclothing.co.uk",
        search_url="https://www.bambooclothing.co.uk/search?query={query}",
    ),
    ScrapeConfig(
        name="theset",
        base_url="https://www.theset.co",
        search_url="https://www.theset.co/search?q={query}",
    ),
]
